services:
  mysql_db_1:
    build:
      context: ./mysql_conf
      dockerfile: Dockerfile
      args:
        CONFIG: node1.cnf
    container_name: mysql_db_1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: session_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - mysql_data_1:/var/lib/mysql
    ports:
      - "3306:3306"

  mysql_db_2:
    build:
      context: ./mysql_conf
      dockerfile: Dockerfile
      args:
        CONFIG: node2.cnf
    container_name: mysql_db_2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: session_db
      # Should Not create the application user on this replica during init
      # It will be created once on mysql_db_1 and replicated via GTID
    volumes:
      - mysql_data_2:/var/lib/mysql
    ports:
      - "3307:3306"

  mysql_db_3:
    build:
      context: ./mysql_conf
      dockerfile: Dockerfile
      args:
        CONFIG: node3.cnf
    container_name: mysql_db_3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: session_db
      # Should Not create the application user on this replica during init
      # It will be created once on mysql_db_1 and replicated via GTID
    volumes:
      - mysql_data_3:/var/lib/mysql
    ports:
      - "3308:3306"

  server_1:
    build: ./serverA
    container_name: server_1
    ports:
      - "8001:8000"
    volumes:
    - ./serverA:/var/www/html
    - ./haproxy:/var/www/html/haproxy  
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpass
      - DB_NAME=session_db

  server_2:
    build: ./serverA
    container_name: server_2
    ports:
      - "8002:8000"
    volumes:
      - ./serverA:/var/www/html
      # - ./haproxy:/var/www/html/haproxy  
    environment:
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=userpass
      - DB_NAME=session_db

  haproxy:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    container_name: haproxy
    ports:
      - "8080:8080"
      - "33066:3306"
    depends_on:
      - mysql_db_1
      - mysql_db_2
      - mysql_db_3
      - server_1
      - server_2
      - haproxy_web
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  haproxy_web:
    build: ./haproxy/web
    container_name: haproxy_web
    ports:
      - "1234:1234"
    volumes:
      - ./haproxy/web:/var/www/html
      - ./haproxy:/var/www/html/haproxy

volumes:
  mysql_data_1:
  mysql_data_2:
  mysql_data_3:
